name: "configuration variable project"

on: 
  push:
    branches: ["main"]
    
evn:
  car: BMW
job:
  "introducing the car for the race":
    runs-on: ubuntu-latest
    evn:
      overseas: Paris
      
    steps:
    
      - name: "showing the winning car"
        run: echo "$First_Name will be going $overseas with his $car for the ${{vars.GAME}}"
      
     evn:
        First_Name: Ebibo
    
