name: Variable for workflow

on: 
   push:
   branches: ["main"] 

env:
   cloud: Amazon Web Service

jobs:
   Introduction

runs-on: ubuntu-latest

env:
   Greetings: How far

steps:

-name: "introducing the order of the day"concurrency: 
run: echo "$Greetings $First_name is using $cloud"

env:
   First_name: Ebiks4real
